### ISSUE TITLE
Update Packagist to mark package as abandoned in favor of doctrine/instantiator

### ISSUE THREAD

**Issue by adduc** [Ocramius/Instantiator#21]
When packages are marked as abandoned within Packagist, a replacement package can be specified. This allows users to easily see the package is no longer suggested for new development.

To implement this, the maintainer of the package should be able to navigate to https://packagist.org/packages/ocramius/instantiator/abandon and follow the instructions.
### Mockup:

![cropped](https://cloud.githubusercontent.com/assets/44527/7569521/fd04b514-f7ce-11e4-869f-0cc21705114b.png)

**Comment by Ocramius** [comment]
The package is not really abandoned, but whatever.

Done :)
